services:
  kafka:
    container_name: kafka-broker
    image: bitnamilegacy/kafka:4.0.0-debian-12-r10
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_KRAFT_CLUSTER_ID: mk-1
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data
    volumes:
      - kafka_data:/bitnami/kafka/data

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8080:8080"

  kafgen:
    container_name: kafka-generator
    build:
      context: .
      dockerfile: kafgen/Dockerfile
    environment:
      KAFKA_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    ports:
      - "8084:8080"

  ingestion:
    container_name: ingestion-service
    build:
      context: .
      dockerfile: ingestion/Dockerfile
    environment:
      PROCESSING_URL: http://processing:8082
      KAFKA_BOOTSTRAPSERVERS: kafka:9092
      MONGO_USER: mongo
      MONGO_PASSWORD: mongo
    depends_on:
      - kafka
      - mongo
      - processing
    ports:
      - "8081:8081"

  mongo:
    container_name: mongo-database
    image: mongodb/mongodb-community-server:7.0-ubi8
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: raw_orders
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  processing:
    container_name: processing-service
    build:
      context: .
      dockerfile: processing/Dockerfile
    ports:
      - "8082:8082"

volumes:
  kafka_data:
  mongodb_data: