services:
  kafka:
    image: bitnamilegacy/kafka:4.0.0-debian-12-r10
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_KRAFT_CLUSTER_ID: mk-1
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 2
      KAFKA_CFG_MESSAGE_MAX_BYTES: 32768
      KAFKA_CFG_NUM_PARTITIONS: 4
    volumes:
      - kafka_data:/bitnami/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8080:8080"

  kafgen:
    build:
      context: .
      dockerfile: kafgen/Dockerfile
    depends_on:
      - kafka
    ports:
      - "8084:8080"

  ingestion:
    build:
      context: .
      dockerfile: ingestion/Dockerfile
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      # URLs до других сервисов
      SERVICE_B_URL: http://service-b:8080
    ports:
      - "8081:8080"

  processing:
    build:
      context: .
      dockerfile: processing/Dockerfile
#    depends_on:
#      - redis
    environment:
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # URLs до других сервисов
      SERVICE_C_URL: http://service-c:8080
    ports:
      - "8082:8080"

  fulfillment:
    build:
      context: .
      dockerfile: fulfillment/Dockerfile
    depends_on:
#      - postgres
      - kafka
    environment:
    # PostgreSQL
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/service_c_db
      DATASOURCE_USERNAME: user
      DATASOURCE_PASSWORD: password
      # Kafka
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8083:8080"

volumes:
  kafka_data: