spring:
  application:
    name: fulfillment
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: ${DATASOURCE_URL}
    password: ${DATASOURCE_PASSWORD}
    username: ${DATASOURCE_USERNAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    com:
      markellowww:
        fulfillment:
          DEBUG