spring:
  application:
    name: kafgen
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAPSERVERS}
    producer:
      acks: all
      retries: 5
      batch-size: 16384
      enable-idempotence: true
      max-in-flight-requests-per-connection: 5
      linger-ms: 5
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true
  model-converters:
    hateoas-converter:
      enabled: false
logging:
  level:
    com:
      markellowww:
        kafgen:
          DEBUG