spring:
  application:
    name: ingestion
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/raw_orders?authSource=admin
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAPSERVERS}
    consumer:
      group-id: ingestion-group
      auto-offset-reset: earliest
      isolation-level: read_committed
      heartbeat-interval: 15000
      max-poll-interval: 300000
      session-timeout-ms: 45000
logging:
  level:
    com:
      markellowww:
        ingestion:
          DEBUG